### ISSUE TITLE
Changing FPS is not working 

### ISSUE THREAD

**Issue by xiaopao2014** [saki4510t/ScreenRecordingSample#21]
`
public MediaScreenEncoder(final MediaMuxerWrapper muxer, final MediaEncoderListener listener,
		final MediaProjection projection, final int width, final int height, final int density,
		final int _bitrate, final int _fps) {

		super(muxer, listener, width, height);
		mMediaProjection = projection;
		mDensity = density;
		fps =  _fps;
		bitrate = (_bitrate > 0) ? _bitrate : calcBitRate(_fps);
		final HandlerThread thread = new HandlerThread(TAG);
		thread.start();
		mHandler = new Handler(thread.getLooper());
	}

`

when i pass 60 or 30 for _fps， i got same frame rate 

![image](https://user-images.githubusercontent.com/7996455/61205200-05d3bd00-a722-11e9-82ee-e350c6bc761f.png)

![企业微信截图_15631810927369](https://user-images.githubusercontent.com/7996455/61205238-1b48e700-a722-11e9-9226-9925dfb0acff.png)
![企业微信截图_15631811407651](https://user-images.githubusercontent.com/7996455/61205239-1b48e700-a722-11e9-8ebc-0784c28856b3.png)

**Comment by xiaopao2014** [comment]
ok i found the problem, the fps is decide by the media projection ,not by the param i passed in.

**Comment by icekloud** [comment]
> ok i found the problem, the fps is decide by the media projection ,not by the param i passed in.

excuse me, can I ask you how you managed to solve it?
